---
title: "Data Descriptor - Manuscript Figures"
output:
  github_document:
    html_preview: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

```{r packages}

library(tidyverse)
library(magrittr)
library(PNWColors)
library(soilpalettes)
library(googlesheets4)
library(whistledown)
library(sf) # for map

options(scipen = 9999)

```

```{r ggplot_theme}

theme_kp <- function() {  # this for all the elements common across plots
  theme_bw() %+replace%
    theme(legend.position = "top",
          legend.key=element_blank(),
          legend.title = element_text(size = 14, hjust = 0),
          legend.text = element_text(size = 12),
          legend.key.size = unit(1.5, 'lines'),
          legend.background = element_rect(colour = NA),
          panel.border = element_rect(color="black",linewidth=1, fill = NA),
          
          plot.title = element_text(hjust = 0, size = 14),
          axis.text = element_text(size = 14, color = "black"),
          axis.title = element_text(size = 14, face = "bold", color = "black"),
          
          # formatting for facets
          panel.background = element_blank(),
          strip.background = element_rect(colour="white", fill="white"), #facet formatting
          panel.spacing.x = unit(1, "lines"), #facet spacing for x axis
          panel.spacing.y = unit(1.5, "lines"), #facet spacing for x axis
          strip.text.x = element_text(size=14, face="bold"), #facet labels
          strip.text.y = element_text(size=14, face="bold", angle = 270) #facet labels
    )
}
theme_set(theme_kp())

```

```{r load_files}

# METADATA
import_metadata = function(FILEPATH, PATTERN){
  
  filePaths <- list.files(path = FILEPATH, pattern = PATTERN, full.names = TRUE)
  dat <- do.call(bind_rows, lapply(filePaths, function(path) {
    df <- read_csv(path) %>% mutate_all(as.character)
    df}))
}
metadata = import_metadata(FILEPATH = "1-data/metadata", PATTERN = ".csv") %>% 
  distinct(Proposal_ID, Sampling_Set, .keep_all = T)

# BGC DATA
import_data = function(FILEPATH, PATTERN){
  
  filePaths <- list.files(path = FILEPATH, pattern = PATTERN, full.names = TRUE)
  dat <- do.call(bind_rows, lapply(filePaths, function(path) {
    df <- read_csv(path)
    df}))
}
bgc = import_data(FILEPATH = "1-data/bgc_data", PATTERN = "biogeochemistry") %>% 
  mutate(Proposal_ID = as.character(Proposal_ID),
         Sampling_Set = as.character(Sampling_Set)) %>% 
  left_join(metadata)

```

---

## MAP AND SAMPLE COUNT

```{r map_data}


neonDomains <- read_sf("NEONDomains_2024", layer="NEON_Domains")
#neonMercator <- st_transform(neonDomains, crs="+proj=merc")

## create a df with site coordinates and labels
sites = metadata %>% 
  separate(lat_lon, sep = ",", into = c("lat", "lon"), remove = F) %>% 
  dplyr::select(Proposal_ID, Sampling_Set, lat, lon, call) %>% 
  mutate(lat = parse_number(lat),
         lon = parse_number(lon)) 

```

```{r map_plot, fig.height=8, fig.width=12}

baseplot =   
  ggplot() + 
  geom_sf(data = neonDomains, color = "black", aes(fill = domainID), show.legend = F, alpha = 0.5, size = 0) + 
  geom_sf_text(data = neonDomains, color = "black", aes(label = domainID), fill = NA)+
  theme(legend.background = element_rect(fill = alpha("white", 0.0)), 
        legend.key = element_rect(fill = "transparent"), 
        legend.position = c(0.85, 0.1),
        axis.text = element_blank()) + 
  geom_point(data = sites %>% filter(call != "1000Soils") %>% filter(Proposal_ID != "61049"), 
             aes(lon, lat),
             size = 2, color = "black", shape = 19)+
    geom_point(data = sites %>% filter(Proposal_ID == "61049"), 
             aes(lon, lat),
             shape = 4, size = 4, color = "black", stroke = 1.5)+
  cowplot::theme_map() + 
  labs(x = "", y = "")+
  #scale_fill_manual(values = pnw_palette("Bay", 20))+
  #scale_fill_manual(values = whistledown_palette("featherington", 20))+
  scale_fill_manual(values = microViz::distinct_palette(n = 20, pal = "kelly"))+
  NULL   

usa = 
  baseplot + 
  coord_sf(xlim = c(-130, -65), ylim = c(19, 50), expand = F)+
  NULL  

ak = 
  baseplot +
  coord_sf(xlim = c(-180, -120), ylim = c(50, 75), expand = F)+
  NULL  

hi = 
  baseplot + 
  coord_sf(xlim = c(-162, -152), ylim = c(18, 23), expand = F)+
  NULL  

gg_map = 
  usa + 
  annotation_custom(
    ggplotGrob(ak), 
    xmin = -130, xmax = -110, ymin = 10, ymax = 40)+
  annotation_custom(
    ggplotGrob(hi), 
    xmin = -115, xmax = -100, ymin = 12, ymax = 32)+
  theme_kp()


gg_map
```

Note: The points represent all sampling locations (660 entries). NEON sites are marked with "X".


```{r site_counts_ecoregion, fig.height=9, fig.width=14}

metadata_columns = 
  metadata %>% 
#  distinct(call, Proposal_ID, Sampling_Set, ecoregion, soil_type, cur_land_use) %>% 
  force()

summary_ecoregions = 
  metadata_columns %>% 
  filter(call != "1000Soils") %>% 
  group_by(ecoregion) %>% 
  dplyr::summarise(n = n()) %>% 
  full_join(neonDomains %>% dplyr::select(domainID, domainName), by = c("ecoregion" = "domainName")) %>% 
  dplyr::select(-geometry) %>% 
#  mutate(n = replace_na(n, 0)) %>% 
  mutate(label = paste0(domainID, " (", n, ")"),
         label2 = paste0(domainID, "\n (", n, ")"))

gg_ecoregion = 
  summary_ecoregions %>% 
  #  filter(n > 0) %>% 
  ggplot(aes(y = reorder(domainID, n), x = n, color = domainID))+
  geom_segment(aes(yend = reorder(domainID, n), xend = 2.5), linewidth = 12, alpha = 0.5)+
  geom_text(aes(label = label), 
            #position = position_nudge(y = -0.4), 
            hjust = -0.1, size = 6, alpha = 1,
            #color = "black", 
            fontface = "bold")+
  xlim(0, 110)+
  #  labs(title = "A: Sampling locations by soil type")+
  #scale_color_manual(values = soil_palette("redox2", 12))+
  #scale_color_manual(values = whistledown_palette("queen", 17))+
  scale_color_manual(values = microViz::distinct_palette(n = 20, pal = "kelly"), drop = F)+
  
  theme_void()+
  theme(#axis.text.x = element_text(hjust = 1, size = 14),
    #axis.text.y = element_blank(),
    legend.position = "none",
    plot.title = element_text(size = 16, face = "bold"),
    plot.background = element_rect(linewidth = 1, color = "black", fill = NA),
    plot.margin = margin(1, 1, 1, 1))


gg_ecoregion2 = 
  summary_ecoregions %>% 
#  filter(n > 0) %>% 
  ggplot(aes(x = reorder(domainID, -n), y = n, color = domainID))+
  geom_segment(aes(xend = reorder(domainID, -n), yend = 2.5), linewidth = 12, alpha = 0.5)+
  geom_text(aes(label = label2), 
            position = position_nudge(y = 5), 
            #hjust = -0.1, 
            size = 6, alpha = 1,
            #color = "black", 
            fontface = "bold")+
  ylim(0, 110)+
  #  labs(title = "A: Sampling locations by soil type")+
  #scale_color_manual(values = soil_palette("redox2", 12))+
  #scale_color_manual(values = whistledown_palette("queen", 17))+
  scale_color_manual(values = microViz::distinct_palette(n = 20, pal = "kelly"), drop = F)+
  
  theme_void()+
  theme(#axis.text.x = element_text(hjust = 1, size = 14),
    #axis.text.y = element_blank(),
    legend.position = "none",
    plot.title = element_text(size = 16, face = "bold"),
   # plot.background = element_rect(linewidth = 1, color = "black", fill = NA),
    plot.margin = margin(1, 1, 1, 1))




gg_ecoregion2
```

```{r map_ecoregion, eval=FALSE, fig.height=16, fig.width=12}

cowplot::plot_grid(gg_map, gg_ecoregion,
                   nrow = 1,
                   labels = c("A", "B"),
                   align = "hv", axis = "tblr", rel_heights = c(1, 1), rel_widths = c(1, 0.6))

```

```{r site_counts}

metadata_columns = 
  metadata %>% 
#  distinct(call, Proposal_ID, Sampling_Set, ecoregion, soil_type, cur_land_use) %>% 
  force()

summary_soil_orders = 
  metadata_columns %>% 
  filter(call != "1000Soils") %>% 
  group_by(soil_type) %>% 
  dplyr::summarise(n = n()) %>% 
  mutate(label = paste0(soil_type, " (", n, ")"))

gg_soil_orders = 
  summary_soil_orders %>% 
  ggplot(aes(y = reorder(soil_type, n), x = n, color = soil_type))+
  geom_segment(aes(yend = reorder(soil_type, n), xend = 2.5), linewidth = 10)+
  geom_text(aes(label = label), 
            #position = position_nudge(y = -0.4), 
            hjust = -0.1, size = 6, alpha = 1,
            #color = "black", 
            fontface = "bold")+
  xlim(0, 300)+
  labs(title = "A: Sampling locations by soil type
       ")+
  #scale_color_manual(values = soil_palette("redox2", 12))+
  scale_color_manual(values = whistledown_palette("queen", 12))+
  theme_void()+
  theme(#axis.text.x = element_text(hjust = 1, size = 14),
        #axis.text.y = element_blank(),
        legend.position = "none",
        plot.title = element_text(size = 16, face = "bold"),
        plot.background = element_rect(linewidth = 1, color = "black", fill = NA),
        plot.margin = margin(5, 5, 5, 5))


summary_biomes = 
  metadata_columns %>% 
  filter(call != "1000Soils") %>% 
  group_by(env_broad_NEW) %>% 
  dplyr::summarise(n = n()) %>% 
    mutate(label = paste0(env_broad_NEW, " (", n, ")"))

gg_biomes = 
summary_biomes %>% 
    ggplot(aes(y = reorder(env_broad_NEW, n), x = n, color = env_broad_NEW))+
  geom_segment(aes(yend = reorder(env_broad_NEW, n), xend = 2.5), linewidth = 10)+
  geom_text(aes(label = label, x = n), 
            #position = position_nudge(y = -0.4), 
            hjust = -0.1, size = 6,
            #color = "black", 
            fontface = "bold")+
  #scale_color_manual(values = whistledown_palette("simon", 11))+
  scale_color_manual(values = pnw_palette("Sailboat", 11))+
  #scale_color_manual(values = soil_palette("redox2", 11))+
  #  scale_fill_manual(values = whistledown_palette("queen", 4))+
  labs(x = "",
       y = "Count by biome",
       title = "B: Sampling locations by biome
       ")+
  xlim(0, 570)+
  theme_void()+
  theme(#axis.text.x = element_text(hjust = 1, size = 14),
        #axis.text.y = element_blank(),
        legend.position = "none",
        plot.title = element_text(size = 16, face = "bold"),
        plot.background = element_rect(linewidth = 1, color = "black", fill = NA),
        plot.margin = margin(5, 5, 5, 5))

```

```{r site_counts_soils_biomes, fig.height=5, fig.width=10}

cowplot::plot_grid(gg_soil_orders, gg_biomes,
                   nrow = 1,
                   # labels = c("A", "B"),
                   align = "hv", axis = "tblr",
                   scale = 0.95)

```

--- 

How many sites and cores were sampled?

```{r number_projects}
print("number of projects")

number_projects = 
  metadata_columns %>% 
  filter(call != "1000Soils") %>% 
  distinct(call, Proposal_ID) %>% 
  group_by(call) %>% 
  dplyr::summarise(n = n()) 

total_projects = number_projects %>% ungroup() %>% dplyr::summarise(sum = sum(n)) %>% pull()

number_projects %>% 
  knitr::kable()

```

total projects = `r total_projects`


```{r, number_sampling_sets}

print("number of sampling sets")

number_sampling_sets = 
  metadata_columns %>% 
  filter(call != "1000Soils") %>% 
  distinct(call, Proposal_ID, Sampling_Set) %>% 
  group_by(call) %>% 
  dplyr::summarise(n = n()) 

total_sampling_sets = number_sampling_sets %>% ungroup() %>% dplyr::summarise(sum = sum(n)) %>% pull()

number_sampling_sets %>% 
  knitr::kable()

```

total sampling sets = `r total_sampling_sets`


```{r, summary_by_orders}

print("summary by soil orders")

summary_by_order = 
  metadata_columns %>% 
  filter(call != "1000Soils") %>% 
  distinct(call, Proposal_ID, Sampling_Set, soil_type) %>% 
  group_by(soil_type) %>% 
  dplyr::summarise(n = n(),
                   percent = 100 * n/total_sampling_sets,
                   percent = round(percent, 1)) 

summary_by_order %>% 
  knitr::kable()


```



---

## BGC data

```{r bgc, fig.height=10, fig.width=8, eval=FALSE}

gg_ph = 
  bgc %>% 
  ggplot(aes(x = soil_type, y = pH))+
 # geom_violin(color = "black")+
  geom_jitter(width = 0.1, size = 0.5)+
  labs(x = "",
       y = "pH 
       ")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 14))



gg_weom = 
  bgc %>% 
  ggplot(aes(x = soil_type, y = WEOM_TOC_mg_per_kg))+
  #geom_violin(color = "black")+
  geom_jitter(width = 0.1, size = 0.5)+
  labs(x = "",
       y = "Water Extractable 
       Organic Carbon (mg/kg)
       ")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 14))

  
cowplot::plot_grid(gg_ph, gg_weom, nrow = 2, align = "hv", labels = c("A", "B"))

```


### V2

```{r, fig.height=10, fig.width=4}
# df for raincloud plots


## set names and groups
data_groups = 
  tribble(
    ~data_group, ~name, ~name2, 
    "bulk density", "Bulk_density_g_per_cm3", "Bulk Density (g/cm3)",
    "bulk chemistry", "Total_Carbon_percent", "Total C (%)",
    "bulk chemistry", "Total_Nitrogen_percent", "Total N (%)",
    "bulk chemistry", "Total_Sulfur_percent", "Total S (%)",
    "bulk chemistry", "pH", "pH",
    "SOM", "HClExtOM_TOC_mg_per_kg", "HCl-Ext C (mg/kg)",
    "SOM", "HClExtOM_TN_mg_per_kg", "HCl-Ext N (mg/kg)",
    "SOM", "WEOM_TOC_mg_per_kg", "H2O-Ext C (mg/kg)",
    "SOM", "WEOM_TN_mg_per_kg", "H2O-Ext N (mg/kg)",
    "SOM", "MBC_mg_per_kg", "MBC (mg/kg)",
    "SOM", "MBN_mg_per_kg", "MBN (mg/kg)",
    "nutrients", "SO4_S_mg_per_kg","SO4-S (mg/kg)",
    "nutrients", "NH4_N_mg_per_kg", "NH4-N (mg/kg)",
    "nutrients", "NO3_N_mg_per_kg", "NO3-N (mg/kg)",
    "nutrients", "PO4_P_mg_per_kg", "PO4-P (mg/kg)",
    "micronutrients", "B_mg_per_kg", "B (mg/kg)",
    "micronutrients", "Zn_mg_per_kg", "Zn (mg/kg)",
    "micronutrients", "Mn_mg_per_kg", "Mn (mg/kg)",
    "micronutrients", "Cu_mg_per_kg", "Cu (mg/kg)",
    "micronutrients", "Fe_mg_per_kg", "Fe (mg/kg)",
    "texture", "Sand_percent", "Sand (%)",
    "texture", "Silt_percent", "Silt (%)",
    "texture", "Clay_percent", "Clay (%)",
    "cations", "Ca_meq_per_100g", "Ca (meq/100g)",
    "cations", "Mg_meq_per_100g", "Mg (meq/100g)", 
    "cations", "Na_meq_per_100g", "Na (meq/100g)", 
    "cations", "K_meq_per_100g", "K (meq/100g)"
  )





bgc_long = 
  bgc %>% 
 #   filter(env_broad_NEW == "temperate") %>% 
  mutate_all(as.character) %>% 
  pivot_longer(cols = -c(call, , Sample_Name, Proposal_ID, Sampling_Set, Core_Section)) %>% 
  mutate(value = as.numeric(value)) %>% 
  drop_na() %>% 
  left_join(data_groups)

bgc_counts = 
  bgc_long %>% 
  group_by(data_group, name, name2) %>% 
  dplyr::summarise(sum = n(),
                   median = median(value))

```

```{r, fig.height=10, fig.width=4}

plot_rainclouds = function(DATA, COUNTS){
  
  DATA %>% 
 #   filter(!is.na(data_group)) %>% 
    ggplot(aes(x = name2, y = value, fill = name, color = name))+
    see::geom_violinhalf(width = 0.5, position = position_nudge(x = 0.2), color = "black")+
    geom_jitter(width = 0.1)+
    geom_boxplot(width = 0.2, fill = NA, color = "black", outliers = F)+#
    geom_text(data = COUNTS, aes(y = median, label = paste("n =", sum)), color = "black",
              position = position_nudge(-0.3), hjust = 0, size = 4)+
    labs(x = "",
         y = "")+
    facet_wrap(~name2, scales = "free", ncol = 1,
               strip.position = "bottom")+
    scale_y_log10()+
    theme(
      plot.background = element_rect(color = "black", linewidth = 1),
      panel.grid = element_blank(),
      axis.text.y = element_blank(),
      legend.position = "none",
      strip.placement = "outside",
      panel.border = element_blank(),
      axis.line.x = element_line(),
      axis.ticks.y = element_blank(),
      panel.spacing.y = unit(2, "lines"), #facet spacing for x axis
    plot.margin = margin(1, r = 3, 1, 1)

      )+
    coord_flip()
  
}

```

```{r raincloud_SOM, fig.height=12, fig.width=5}
plot_rainclouds(DATA = bgc_long %>% filter(data_group == "SOM"), COUNTS = bgc_counts %>% filter(data_group == "SOM"))+ 
#  scale_fill_manual(values = pnw_palette("Starfish", 6)) + scale_color_manual(values = pnw_palette("Starfish", 6))+
  scale_fill_manual(values = whistledown_palette("daphne", 6)) + scale_color_manual(values = whistledown_palette("daphne", 6))

```

```{r raincloud_bulk, fig.height=8, fig.width=5}
plot_rainclouds(DATA = bgc_long %>% filter(data_group == "bulk chemistry" & name != "Total_Sulfur_percent"), 
                COUNTS = bgc_counts %>% filter(data_group == "bulk chemistry" & name != "Total_Sulfur_percent")) + scale_y_continuous()+
  scale_fill_manual(values = whistledown_palette("daphne", 3)) + scale_color_manual(values = whistledown_palette("daphne", 3))

```

```{r raincloud_nutrients, fig.height=8, fig.width=5}
plot_rainclouds(DATA = bgc_long %>% filter(data_group == "nutrients"), COUNTS = bgc_counts %>% filter(data_group == "nutrients")) + scale_y_log10()+
  scale_fill_manual(values = whistledown_palette("daphne", 4)) + scale_color_manual(values = whistledown_palette("daphne", 4))

```

```{r raincloud_cations, fig.height=10, fig.width=5}
plot_rainclouds(DATA = bgc_long %>% filter(data_group == "cations"), COUNTS = bgc_counts %>% filter(data_group == "cations"))+
  scale_fill_manual(values = whistledown_palette("daphne", 4)) + scale_color_manual(values = whistledown_palette("daphne", 4))

```

```{r raincloud_metals, fig.height=10, fig.width=5}
plot_rainclouds(DATA = bgc_long %>% filter(data_group == "micronutrients"), COUNTS = bgc_counts %>% filter(data_group == "micronutrients"))+
    scale_fill_manual(values = whistledown_palette("daphne", 5)) + scale_color_manual(values = whistledown_palette("daphne", 5))

```


```{r, eval=F}





bgc %>% 
  ggplot(aes(x = Total_Sulfur_percent, y = SO4_S_mg_per_kg, color = Core_Section))+
  geom_point()


x=
  bgc_long %>%
  dplyr::select(Sample_Name, name2, value) %>%
  drop_na() %>% 
  distinct() %>% 
  pivot_wider(names_from = "name2") %>% 
  #  dplyr::select(where(is.numeric)) %>% 
  plot()


(bgc %>% 
  ggplot(aes(x = Total_Carbon_percent, y = Total_Nitrogen_percent, color = Core_Section))+
  geom_point() + 
  geom_smooth(method = "lm", se = F)) %>% 
  ggMarginal(type = "histogram")


(bgc %>% 
  ggplot(aes(x = Ca_meq_per_100g, y = Mg_meq_per_100g, color = Core_Section))+
  geom_point() + 
  geom_smooth(method = "lm", se = F)) %>% 
  ggMarginal(type = "histogram")


```




---

## FTICR


```{r icr_processing}

## fticr processing


import_files = function(FILEPATH){
  
  # identify the .zip files and unzip them as csv files
  # the csv files will be saved in the parent directory (these are temporary files, will be deleted at the end)
  zip_filePaths <- list.files(path = FILEPATH, pattern = ".zip", full.names = TRUE, recursive = TRUE)
  zip_filePaths %>% lapply(unzip)
  
  # now, identify all the fticrWEOM csv files that we just extracted 
  csv_filePaths <- list.files(pattern = "fticrWEOM", full.names = TRUE)
  
  # read and combine the fticrWEOM csv files
  icr_dat <- do.call(bind_rows, lapply(csv_filePaths, function(path) {
    
    data = read.csv(path) %>% 
      mutate(source = basename(path)) # add file name
    
  }))
  
  # finally, delete the temporary files from the parent directory
  file.remove(csv_filePaths)
  
  # this is our final output
  icr_dat
}
icr_report = import_files("1-data/fticr")

#
# II. Initial cleaning ----
### Create molecular metadata file (`mol`)

mol = 
  icr_report %>% 
  dplyr::select(`Molecular.Formula`, C,H,O,N,P,S) %>% 
  rename(molecular_formula = `Molecular.Formula`) %>% 
  distinct()

## Now, we want to process the `mol` file and calculate various indices

## (a) indices
## - AImod (aromatic index), calculated based on [Koch and Dittmar (2016)](https://doi.org/10.1002/rcm.7433)
## - NOSC (nominal oxidation state of carbon), calculated based on [Riedel et al. 2012](https://doi.org/10.1021/es203901u)
## - GFE (Gibbs Free Energy of carbon oxidation), calculated from NOSC, as per [LaRowe & Van Cappellen 2011](https://doi.org/10.1016/j.gca.2011.01.020)
## - H/C, or the ratio of hydrogen to carbon in the molecule
## - O/C, or the ratio of oxygen to carbon in the molecule

mol = 
  mol %>% 
  mutate(across(c("N","S","P"), ~replace_na(.,0)), # convert all blank cells to 0 to help with calculations
         AImod = round((1 + C - (0.5*O) - S - (0.5 * (N+P+H)))/(C - (0.5*O) - S - N - P), 4),
         # some AImod values may be NA, or Inf, or -Inf. Change those to 0
         AImod = ifelse(is.na(AImod), 0, AImod),
         AImod = ifelse(AImod == "Inf", 0, AImod),
         AImod = ifelse(AImod == "-Inf", 0, AImod),
         NOSC = round(4 - ((4*C + H - 3*N - 2*O + 5*P - 2*S)/C),4),
         GFE = 60.3 - (28.5 * NOSC),
         HC = round(H/C, 2),
         OC = round(O/C, 2)
  )

## (b) Elemental class
## We can also group the molecules based on the elemental composition, i.e. "CHO", "CHONS", "CHONP", "CHONPS" classes

mol = 
  mol %>% 
  mutate(
    # we need to drop any isotopic info (13C, 34S, etc.)
    El = str_remove_all(molecular_formula, "13C|34S|17O|18O|15N"),
    # remove any numbers from the formula to get just the elements
    El = str_remove_all(El, "[0-9]"),
    El = str_remove_all(El, " "))

## (c) molecular class
## Next, we assign classes (aromatic, aliphatic, etc.). These are Van Krevelen classes, typically assigned based on the H/C, O/C, and AImod indices. 
## We calculate three sets of classes; users can use any of these, or assign their own classes as appropriate.
## 
## 1. `Class1` from [Kim et al. 2003](https://doi.org/10.1021/ac034415p) uses H/C and O/C to classify molecules into "lipid", "unsaturated hydrocarbon", "protein", "lignin", "carbohydrate", amino sugar", "tannin", and "condensed hydrocarbon"
## 2. `Class2` from [Seidel et al. 2014](https://doi.org/10.1016/j.gca.2014.05.038) uses H/C, O/C, and AImod to classify molecules into "aromatic", "condensed aromatic", "highly unsaturated compounds including polyphenols/lignins", and "aliphatic"
## 3. `Class3` from [Seidel et al. 2017](https://doi.org/10.3389/feart.2017.00031) includes classes "aromatic", "condensed aromatic", "highly unsaturated compounds including polyphenols/lignins", "carbohydrate", "lipid", "aliphatic", and "aliphatic containing N".
## 

mol = 
  mol %>% 
  mutate(
    Class1 = case_when(HC >= 1.5 & HC <= 2.5 & OC >= 0 & OC <= 0.3 ~ "Lipid",
                       HC >= 0.8 & HC <= 1.5 & OC >= 0.05 & OC <= 0.15 ~ "Unsat Hydrocarbon",
                       HC >= 1.5 & HC <= 2 & OC >= 0.3 & OC <= 0.55 ~ "Protein",
                       HC >= 0.8 & HC <= 1.5 & OC >= 0.28 & OC <= 0.65 ~ "Lignin",
                       HC >= 1.5 & HC <= 2.15 & OC >= 0.7 & OC <= 1 ~ "Carbohydrate",
                       HC >= 1.5 & HC <= 1.8 & OC >= 0.55 & OC <= 0.7 ~ "Amino Sugar",
                       HC >= 0.8 & HC <= 1.5 & OC >= 0.65 & OC <= 1.05 ~ "Tannin",
                       HC >= 0.3 & HC <= 0.8 & OC >= 0.12 & OC <= 0.7 ~ "Cond Hydrocarbon",
                       TRUE ~ "Other"),
    Class2 = case_when(AImod > 0.66 ~ "condensed aromatic",
                       AImod <= 0.66 & AImod > 0.50 ~ "aromatic",
                       AImod <= 0.50 & HC < 1.5 ~ "unsaturated/lignin",
                       HC >= 1.5 ~ "aliphatic",
                       TRUE ~ "other"),
    Class3 = case_when(AImod > 0.66 ~ "condensed aromatic",
                       AImod <= 0.66 & AImod > 0.50 ~ "aromatic",
                       AImod <= 0.50 & HC < 1.5 ~ "unsaturated/lignin",
                       HC >= 2.0 & OC >= 0.9 ~ "carbohydrate",
                       HC >= 2.0 & OC < 0.9 ~ "lipid",
                       HC < 2.0 & HC >= 1.5 & N == 0 ~ "aliphatic",
                       HC < 2.0 & HC >= 1.5 & N > 0 ~ "aliphatic+N",
                       TRUE ~ "other")
  )
         

## this file now contains most of the info needed to interpret the data across different samples.

### Create `dat`

## This dataframe contains info about the samples being analyzed, i.e., which peaks were identified in which sample.  
## We will clean this up and eventually merge with the `mol` dataframe.

dat = 
  icr_report %>% 
  dplyr::select(source, Molecular.Formula, Calculated.m.z, contains("Peak.Area")) %>% 
  janitor::clean_names() %>% 
  separate(source, sep = "_", into = c("icr", "Proposal_ID", "Sampling_Set", "Core_Section", "Rep")) %>% 
  mutate(Rep = parse_number(Rep),
         sample_name = paste0(Proposal_ID, "_", Sampling_Set, "_", Core_Section)) %>% 
  dplyr::select(-icr)


#### 3 acquisitions

## Each sample/rep was analyzed 3 times on the machine (i.e., 3 acquisitions, or instrument replicates).  
## For robust analysis, some users may choose to only include peaks identified across multiple acquisitions (e.g., peaks seen in 2 of 3 acqusitions, or peaks seen in all acquisitions). The choice is dependent on the user and the questions being asked.  
## For this example, we only include peaks identified in 2 of the 3 acquisitions. 

## acquisition reps
# an easy way to do this is to convert all the peak areas to binary 0/1 and then add them up. 
# if the sum is 2 or more, that means the peak was seen in 2 or more acquisitions

dat_acq = 
  dat %>% 
  mutate(peak_area_1 = case_when(peak_area_1 > 0 ~ 1),
         peak_area_2 = case_when(peak_area_2 > 0 ~ 1),
         peak_area_3 = case_when(peak_area_3 > 0 ~ 1),
         acquisition_count = peak_area_1 + peak_area_2 + peak_area_3,
         acquisition_KEEP = acquisition_count == 3) %>% 
  filter(acquisition_KEEP) %>% 
  dplyr::select(-c(contains("peak_area"), contains("acquisition")))


#### 3 replicates

## Each sample was extracted 3 times. We apply the same 2/3 replication filter as above. This is also user-dependent.
## Now, we only select molecules that were identified in 2/3 of the total reps

# identify the number of replicates for each sample
# for this MONet workflow, each sample has 3 replicates, so it is straightforward.
# But this code can be used even if there was uneven replication across different samples.

# now, calculate the occurrence of each peak 
dat_reps = 
  dat_acq %>% 
  group_by(Proposal_ID, Sampling_Set, Core_Section, molecular_formula) %>% 
  dplyr::mutate(peak_reps = n()) %>%
  ungroup() %>% 
  mutate(KEEP = peak_reps == 3) %>% 
  filter(KEEP) %>% 
  dplyr::select(-KEEP)

dat_final = 
  dat_reps %>% 
  dplyr::select(-c(Rep, peak_reps)) %>% 
  distinct()

## This is the list of all the peaks "present" (identified) in our samples.
## Now, combine this file with the `mol` file we generated above.

icr_processed = 
  dat_final %>% 
  left_join(mol) %>% 
  mutate(Core_Section = factor(Core_Section, levels = c("TOP", "BTM")))


#

  

```


```{r icr_vk}

# Van Krevelens -----------------------------------------------------------

# mod
classification <- tribble(
  ~Class, ~OC_low, ~OC_high, ~HC_low, ~HC_high,
  'Lipid', 0, 0.3, 1.5, 2.5,
  'Unsat. HC', 0.05, 0.15, 0.8, 1.5,
  'Cond. HC', 0.12, 0.7, 0.3, 0.8,
  'Protein', 0.3, 0.55, 1.5, 2,
  'Amino sugar', 0.55, 0.7, 1.5, 1.8,
  'Carbohydrate', 0.7, 1, 1.5, 2.15,
  'Lignin', 0.28, 0.65, 0.8, 1.5,
  'Tannin', 0.65, 1.05, 0.8, 1.5, 
) %>% 
  mutate(label_x = (OC_low + OC_high) / 2,
         label_y = (HC_low + HC_high) / 2)


## Compound class rectangles (for plotting of Van Krevelen diagrams) ----

class_rect <-  geom_rect(data = classification,
                         aes(xmin = OC_low,
                             xmax = OC_high,
                             ymin = HC_low,
                             ymax = HC_high),
                         color = 'black',
                         fill = NA,
                         linewidth = 1,
                         inherit.aes = FALSE, 
                         linetype = 'dashed')

rect_label <- geom_label(data = classification,
                         aes(x = label_x,
                             y = label_y,
                             label = Class),
                         inherit.aes = FALSE,
                         size = 6)



icr_processed %>% 
  ggplot(aes(x = OC, y = HC, color = Class1))+
  geom_point(show.legend = F)+
  class_rect+
  rect_label+
  scale_color_manual(values = whistledown_palette("queen", 9))+
  facet_wrap(~Core_Section)

```

```{r icr_unique}

## unique
unique = 
  icr_processed %>% 
  group_by(Proposal_ID, Class1, molecular_formula) %>% 
  dplyr::mutate(n = n())

gg_vankrev_unique = 
  unique %>% 
  filter(n == 2) %>% 
  ggplot(aes(x = OC, y = HC))+
  geom_point(size = 2, color = "grey90", alpha = 0.4)+
  geom_point(data = unique %>% filter(n == 1), size = 1, aes(color = Class1))+
  
  class_rect+
  rect_label+
  scale_color_manual(values = whistledown_palette("queen", 9))+
  labs(x = "O/C",
       y = "H/C")+
  facet_wrap(~Core_Section)+
  NULL

```

```{r icr_relabund}

rel_abundance = 
  icr_processed %>% 
  group_by(Proposal_ID, Sampling_Set, Core_Section, sample_name, Class1) %>% 
  dplyr::summarise(count = n()) %>% 
  group_by(Proposal_ID, Sampling_Set, Core_Section, sample_name) %>% 
  dplyr::mutate(total = sum(count),
                relabund = 100 * count/total,
                relabund = round(relabund, 2)
  ) %>% 
  mutate(Core_Section = factor(Core_Section, levels = c("TOP", "BTM"))) %>% 
  ungroup()

rel_abundance %>% 
  dplyr::select(sample_name, Class1, relabund) %>% 
  pivot_wider(names_from = "Class1", values_from = "relabund") %>% 
  knitr::kable()

gg_relabund = 
  rel_abundance %>% 
  ggplot(aes(x = Core_Section, y = relabund, fill = Class1)) +
  geom_bar(stat = "identity")+
  labs(x = "",
       y = "Relative Abundance (%)",
       fill = "Compund Class")+
  # facet_wrap(~Proposal_ID)+
  scale_fill_manual(values = whistledown_palette("queen", 9))

```

```{r icr_combined, fig.height=7, fig.width=20}

cowplot::plot_grid(gg_vankrev_unique + theme(legend.position = "none"), 
                   gg_relabund + theme(legend.position = "right"), 
                   rel_widths = c(2, 1), align = "hv", axis = "bt",
                   labels = c("A", "B"))

```

```{r icr_combined2, fig.height=10, fig.width=12}

cowplot::plot_grid(gg_vankrev_unique + theme(legend.position = "none"), 
                   gg_relabund + theme(legend.position = "bottom") + coord_flip(), 
                   ncol = 1,
                   rel_heights = c(2, 1), align = "hv", axis = "bt",
                   labels = c("A", "B"))

```

---

## HYPROP

```{r hyprop}

options(scipen = 9999)
hyprop_params = read.csv("1-data/HYPROP_FY24_L2_summary.csv")


# x = runif(2000, min = 10^-4, max = 10^6)
# 
# x1 = runif(500, min = 10^-4, max = 10)
# x2 = runif(5000, min = 10, max = 10^3)
# x3 = runif(5000, min = 10^3, max = 10^5)
# x4 = runif(5000, min = 10^5, max = 10^8)
# x_all = c(x1, x2, x3, x4)

x_all = exp(runif(500, min = -1, max = 15))


hyprop_wrc = 
  cross_join(hyprop_params, x_all, copy = T) %>% 
#  filter(Proposal_ID == "61389") %>% 
#  filter(Sampling_Set %in% c(3, 21, 24)) %>% 
  rename(h = y) %>% 
  mutate(m = 1 - (1/n),
         theta = theta_r_cm3_per_cm3 + (theta_s_cm3_per_cm3 - theta_r_cm3_per_cm3) / (1 + (alpha_per_cm * h)**n)**m,
         #         h_MPa = h/1000,
         h_kPa = h/10,
         h_MPa = h_kPa/1000
  ) %>% 
  mutate(Proposal_ID = as.character(Proposal_ID),
         Sampling_Set = as.character(Sampling_Set),
         sample_name = paste0(Proposal_ID, "_", Sampling_Set)) %>% 
  left_join(metadata)

# 1mm = 10Pa
# 1cm = 100Pa
# 10cm = 1kPa
# 10,000cm = 1MPa

hyprop_wrc %>% 
  filter((Proposal_ID == "61389" & 
            Sampling_Set %in% c(3, 5, 8, 12, 14, 21))) %>% 
  ggplot(aes(x = h_kPa, y = theta * 100, color = as.character(Sampling_Set)))+
  #geom_point(show.legend = F)+
  geom_line(linewidth = 1.5, show.legend = F)+
  scale_x_log10(limits = c(0.5, 1e6),
                labels = scales::label_log())+
  scale_color_manual(values = whistledown_palette("penelope", 7))+
  scale_color_manual(values = pnw_palette("Sailboat", 7))+
  labs(x = "Water Potential (kPa)",
       y = "Water Content (% v/v)")+
#  facet_wrap(~Proposal_ID)+
  NULL


  ##  hyprop_wrc %>% 
  ##    mutate(sample_name = paste0(Proposal_ID, "_", Sampling_Set)) %>% 
  ##    filter(Proposal_ID == c("61258", "61086", "61389", "61257")  
  ##           #   Sampling_Set %in% c(3, 5, 8, 12, 14, 21))
  ##           ) %>% 
  ##    ggplot(aes(x = h_kPa, y = theta * 100, color = as.character(sample_name)))+
  ##    #geom_point(show.legend = F)+
  ##    geom_line(linewidth = 1.5, show.legend = T)+
  ##    scale_x_log10(limits = c(0.01, 1e9),
  ##                  labels = scales::label_log())+
  ##  #  scale_color_manual(values = whistledown_palette("penelope", 7))+
  ##  #  scale_color_manual(values = pnw_palette("Sailboat", 7))+
  ##    labs(x = "Water Potential (kPa)",
  ##         y = "Water Content (% v/v)")+
  ##    facet_wrap(~Proposal_ID)+
  ##    NULL


hyprop_wrc %>% 
  filter(Proposal_ID == c("61078", "61093", "61257")) %>%  
#            Sampling_Set %in% c(3, 5, 8, 12, 14, 21))) %>% 
  ggplot(aes(x = h_kPa, y = theta * 100, color = soil_type, group = sample_name))+
  #geom_point(show.legend = F)+
  geom_line(linewidth = 1.5, show.legend = T)+
  scale_x_log10(limits = c(0.01, 1e7),
                labels = scales::label_log())+
#  scale_color_manual(values = whistledown_palette("penelope", 7))+
#  scale_color_manual(values = pnw_palette("Sailboat", 7))+
  labs(x = "Water Potential (kPa)",
       y = "Water Content (% v/v)")+
#  facet_wrap(~Proposal_ID)+
  NULL




```



---

## Session Info 

<details>
  <summary> Session Info </summary>

Date run: `r Sys.Date()`

```{r}
sessionInfo()
```

</details>